apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ogt20rt0e-python 
  janus-idp.io/tekton: ogt20rt0e-python
  backstage.io/kubernetes-id: ogt20rt0e-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ogt20rt0e-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml